server:
  port: 80

#设置feign客户端超时时间 (默认1秒)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况i正常的情况下,两端连接所用的时间 5秒
  ReadTimeout: 5000
  #指的是建立连接蛋从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    com.tang.springcloud.service.PaymentFeignService: debug #日志打印
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 47.106.215.60:8080
        port: 8719 #默认8719端口 假如被占用会自动从8719开始依次加+1扫描，直至找到未被占用的端口
        #client-ip: 42.192.233.207
      eager: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wangcaiwuyou
    url: jdbc:mysql://175.178.218.200:3306/company?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
  # redis 配置
  redis:
    # 地址
    #host:  127.0.0.1
    #host:  r-7xvarjjnaw10tpmqkhpd.redis.rds.aliyuncs.com
    host: 175.178.218.200
    port: 6379
    #password: "MKredis1406"
    password: wangcaiwuyou
    # 数据库索引
    database: 9
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  main:
    allow-bean-definition-overriding: true
  application:
    name: test
management:
  endpoints:
    web:
      exposure:
        include: "*"

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true