ip: '@ip@'
#日期格式化
rocketmq:
  client:
    logPath: /home/logs/rocketmq
# 数据源配置
spring:
  session:
    store-type: redis
  cloud:
    alibaba:
      seata:
    sentinel:
      log:
        dir:  /home/logs/
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB #设置单个文件大小
      max-request-size: 50MB #设置单次请求文件的总大小

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  type-aliases-package: com.wcwy.company.entity
  configuration:
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    auto-mapping-behavior: full
    # 关闭一级缓存 单服务架构中（有且仅有只有一个程序提供相同服务），一级缓存开启不会影响业务，只会提高性能。
    # 微服务架构中需要关闭一级缓存，原因：Service1先查询数据，若之后Service2修改了数据，
    # 之后Service1又再次以同样的查询条件查询数据，因走缓存会出现查处的数据不是最新数据
    local-cache-scope: statement
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/xml,application/json
  port: 7001
knife4j:
  enable: true
  production: '@knife4j.production@'
  basic:
    password: wangcaiwuyou
    username: wangcaiwuyou
  setting:
    enableOpenApi: true
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
  endpoints:
    web:
      exposure:
        include: '*'
weixin:
  url: "https://api.weixin.qq.com"
  appid: "wx23be93997fd676ff"
  appSecret: "e48a4ebf2feea6201dec486dd90af343"


#激活sentinel对feign的支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      useGzipDecoder: true
  httpclient:
    connection-timeout: 6000
    connection-timer-repeat: 3000
    enabled: true
  hystrix:
    enabled: false
  sentinel:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
#SMS
access:
  ketId: LTAI5tSjbbPx6yuaj5YsmFn8
  secret: 8l4M2PtpCeDsYCU4NIYWywYRFVdNOX
  regionId: cn-beijing
  #open: true
  open: '@sms.open@'
# 设置日志级别
logging:
  config: classpath:logback-spring.xml
ribbon:
  eager-load:
    enabled: true #是否开启饥饿加载
    clients: wcwy-post
  ConnectTimeout: 3000 # 设置连接超时时间 default 2000
  ReadTimeout: 5000   # 设置读取超时时间  default 5000
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试  default false
  MaxAutoRetriesNextServer: 2    # 切换实例的重试次数  default 1
  MaxAutoRetries: 10     # 对当前实例的重试次数 default 0